### PR TITLE
chore : Add Screenshots to Readme.md 

### LINKED ISSUE #18: Add screenshots to the README file
Add screenshots to the README file

**Would you like to work on the issue?**

No

### PR DESCRIPTION
**Pull request by aman-g0yaa**
Fixes #18 
**Changes:**
Added  3 screenshots into READ.md file.

Please make sure these boxes are checked before submitting your pull request - thank you!

- [x] Run unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into a single commit by squashing them.

Please add screenshots/GIFs here if there are any changes to the UI below.

### CODE REVIEW

**Comment by immadisairaj** [comment]
@amangoyal2339 why did you close the old PR. this is not a good practice.

Please follow semantic PR guidelines

**Comment by aman-g0yaa** [comment]
@immadisairaj  Sorry , I wont repeat it .

**Comment by immadisairaj** [comment]
@amangoyal2339 change the title and commit to `add` instead of `added`
follow semantic PR guidelines

**Comment by immadisairaj** [comment]
>  Run unit tests with ./gradlew check to make sure you didn't break anything   
>  If you have multiple commits please combine them into a single commit by squashing them.

and also make sure you do this

**Pull request closed without merging**
